# Generated by Django 5.0.2 on 2024-04-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='chat_resp_time',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='shipping_on_time',
        ),
    ]
